README.md
src/rules.js
src/runner.js
src/validate.js
test/rules.spec.js
test/validate.spec.js

- Add optional includeRules / excludeRules configuration options
- Validate option formats. Allow rules to be a string or RegExp expression
- Create `Rules.filter` method to filter states by rules
- Change to use lodash `cloneDeep` method to make object copies
- Update default resolution to `1024x768`
- Update Unit Tests
- Update README docs
```
$ npm test
```

Add IncludeRules / ExcludeRules

---

README.md
src/runner.js
src/validate.js
test/runner.spec.js
test/validate.spec.js

- Support testing multiple resolutions
```javascript
resolutions: [
'1024x768',
{ deviceName: 'iPhone 6' },
{
deviceName: 'iPhone 6 Plus',
deviceOrientation: 'landscape'
}
]
```
- Update printed logs with resolutions
- Update Unit Tests
- Update README docs with new resolution options
```
$ npm test
```

Add Responsive Design Testing

---

src/api.js
src/runner.js
src/tunnel.js
test/api.spec.js
test/runner.spec.js
test/tunnel.spec.js

- Add getTunnelToken api method
- Update Tunnel.connect to include token
- Integrate tunnel token into runner
```
$ npm test
```

Integrate Tunnel token

---

README.md
src/runner.js
src/validate.js
test/validate.spec.js

- Add new `cssAnimations` config option
```
$ npm test
```

Disable CSS Animations

---

README.md
src/runner.js
src/validate.js
test/validate.spec.js

- Add new `initialBaselineBranch` config option
```
$ npm test
```

Add initialBaselineBranch Option

---

README.md
src/runner.js
src/validate.js
test/runner.spec.js
test/validate.spec.js

- Add new `sauce` integration config option
- Add new `browsers` config option
- Add validation rules for new `sauce` and `browsers` option
```
$ npm test
```

Add Sauce Integration and Browsers option

---

src/validate.js
test/validate.spec.js

- Add `browsers` validation to ensure uniqueness
```
$ npm test
```

Ensure browsers are unique

---

src/ci.js
test/ci.spec.js

- Auto-add new `commit` config option
```
$ npm test
```

Auto-add commit hash

---

README.md
src/ci.js
test/ci.spec.js

- Add GitLab CI environment vars
```
$ npm test
```

Support Gitlab CI

---

README.md
src/validate.js

- Add minLayoutPosition config option
- Validate minLayoutPosition
```
$ npm test
```

Expose minLayoutPosition option

---

README.md
src/ci.js
test/ci.spec.js

- Add Buildkite CI support
```
$ npm test
```

Support Buildkite CI

---

src/validate.js
test/validate.spec.js

- Increase state name limit to 200 chars
- Validate step name length
```
$ npm test
```

Increase state name limit to 200 chars

---

README.md
src/ci.js
src/validate.js
test/ci.spec.js
test/validate.spec.js

- Add commit config option
- Handle empty commit value
```
$ npm test
```

Add commit config option

---

README.md
src/validate.js
test/validate.spec.js

- Add baseBranch config option
```
$ npm test
```

Add baseBranch config option

---

src/ci.js
test/ci.spec.js

- Handle PR branch/commit
```
$ npm test
```

Improve Travis CI integration

---

README.md
src/validate.js
test/validate.spec.js

- Add hide config option
```
$ npm test
```

Add Hide Option

---

src/runner.js
src/validate.js
test/runner.spec.js
test/validate.spec.js

- Add beforeEachScript config option
```
$ npm test
```

Add beforeEach option

---

README.md
src/steps.js
src/validate.js
test/steps.spec.js

- Add `mouseDown` step
- Add `mouseUp` step
```
$ npm test
```

Add Mouse Up/Down actions

---

README.md
src/steps.js
src/validate.js
test/steps.spec.js

- Add `cropTo` option to `snapshot` step
- Update validations
```
$ npm test
```

Add cropTo option

---

README.md
src/ci.js
test/ci.spec.js

- Add support for VSTS Builds
```
$ npm test
```

Add VSTS CI support

---

README.md
src/ci.js
src/validate.js
test/ci.spec.js
test/runner.spec.js
test/validate.spec.js

- Add support for VSTS PR branch, number, instance
```
$ npm test
```

VSTS Integration

---

README.md
src/validate.js
test/validate.spec.js

- Add `maxConcurrent` option to sauce config
```
$ npm test
```

Add sauce.maxConcurrent option

---

src/runner.js
src/tunnel.js
test/tunnel.spec.js

- Retry fetch token
- Error when no token on tunnel start
```
$ npm test
```

Retry or error when no token

---

src/ci.js
test/ci.spec.js

- Handle pulling from `ghprb-plugin` environment variables
```
$ npm test
```

Handle Jenkins env vars from ghprb-plugin

---

src/runner.js
src/validate.js
test/runner.spec.js
test/validate.spec.js

- Add screener-runner version to `meta`
- Validate `meta` prop
```
$ npm test
```

Add Meta property

---

src/ci.js
test/ci.spec.js

- Prefix branch name with PR slug when PR source and destination branch names are the same
```
$ npm test
```

Prefix slug when PR src and dest branch names are equal

---

README.md
src/validate.js
test/validate.spec.js

- Add `failOnNewStates` option
```
$ npm test
```

Add failOnNewStates option

---

README.md
src/steps.js
src/validate.js
test/steps.spec.js
test/validate.spec.js

- Add `disableAutoSnapshots` option
- Add `newSessionForEachState` option
- Add `url` step type
- Validate new options
```
$ npm test
```

Add new E2E options

---

README.md
src/validate.js
test/validate.spec.js

- Add `browserStack` integration option
- Validate new options
```
$ npm test
```

Add BrowserStack Integration

---

README.md
src/validate.js
test/validate.spec.js

- Add `ieNativeEvents` option
```
$ npm test
```

Add ieNativeEvents option

---

src/runner.js
src/validate.js
test/validate.spec.js

- Add `shots` and `shotsIndex` options
- Validate new options
```
$ npm test
```

Support screener-shots

---

README.md
src/validate.js
test/validate.spec.js

- Add `compareSVGDOM` option
```
$ npm test
```

Add compareSVGDOM option

---

README.md
src/validate.js
test/validate.spec.js

- Add `disableBranchBaseline` option
```
$ npm test
```

Add disableBranchBaseline option

---

package.json

- Update to latest mocha version 5.2.0
```
$ npm test
```

Update mocha version

---

README.md
src/validate.js
test/validate.spec.js

- Add `minShiftGraphic` option
```
$ npm test
```

Add minShiftGraphic option

---

src/validate.js
test/validate.spec.js

- Update validation option
```
$ npm test
```

Allow empty string in setValue step

---

package-lock.json
package.json
src/api.js

- Add `requestretry`
- Refactor request
```
$ npm test
```

Improve Retries

---

README.md
src/validate.js
test/validate.spec.js

- Add `useNewerBaseBranch` option
- Validate new option values
```
$ npm test
```

Add useNewerBaseBranch option

---

README.md
src/validate.js
test/validate.spec.js

- Add `alwaysAcceptBaseBranch` option
```
$ npm test
```

Add alwaysAcceptBaseBranch option

---

README.md
src/steps.js
test/steps.spec.js

- Add `rtl` step
- Add `ltr` step
```
$ npm test
```

Add RTL/LTR steps

---

README.md
src/steps.js
src/validate.js
test/steps.spec.js
test/validate.spec.js

- Add `cssAnimations` override step
- Validate `cssAnimations` step
```
$ npm test
```

Add cssAnimations step

---

src/runner.js
test/runner.spec.js

- Throw error when no states are found
```
$ npm test
```

Error when no states found

---

package-lock.json
package.json

https://github.com/screener-io/screener-runner/issues/56

Lock down ngrok version

---

src/runner.js
src/validate.js
test/runner.spec.js
test/validate.spec.js

- Add support for includeRules/excludeRules on resolutions
```
$ npm test
```

Add optional include/exclude rules for resolutions

---

src/runner.js
test/runner.spec.js

- Transform step urls to use tunnel address when applicable
```
$ npm test
```

Transform step urls to tunnel address. add unit tests

---

README.md
src/steps.js
src/validate.js
test/steps.spec.js
test/validate.spec.js

- Add new `isPassword` option to `setValue` step
- Update step validations
```
$ npm test
```

Add isPassword option to setValue step

---

README.md
src/validate.js
test/validate.spec.js

- Add `disableConcurrency` option
```
$ npm test
```

Add disableConcurrency option

---

README.md
src/steps.js
src/validate.js
test/steps.spec.js
test/validate.spec.js

- Add new `maxTime` option to click, wait and waitForNotFound step types
- Update step validations
```
$ npm test
```

Add maxTime option to set custom timeouts

---

package.json
src/api.js
src/runner.js
test/api.spec.js
test/runner.spec.js

Add possibility to use a new API endpoint

---

src/tunnel.js
test/tunnel.spec.js

- Wait and retry Ngrok on connnection error
```
$ npm test
```

Retry Ngrok connection

---

README.md
src/validate.js
test/validate.spec.js

- Add additional sauce-specific options: `extendedDebugging`, `tunnelIdentifier`, and `parentTunnel `
- Update option validations
```
$ npm test
```

Add sauce options

---

README.md
src/tunnel.js
test/tunnel.spec.js

- Update tunnel to support https
```
$ npm test
```

Support https tunnel host

---

CHANGELOG.md
README.md

Specify the Sauce Connect version being used in the current repo.

specify sc version

---

CHANGELOG.md

This was mistakenly left over while fixing the requested changes in #81.

Fix incorrect version reference in CHANGELOG

---

CHANGELOG.md
README.md
scripts/install.js
test/install.spec.js

- Update Sauce Connect version to `4.6.2`
```
$ npm test
```

Update SC version to 4.6.2

---

CHANGELOG.md
package-lock.json
package.json

- Update http-proxy to 1.18.1
```
$ npm test
```

Update http-proxy dep

---

CHANGELOG.md
README.md
src/validate.js
test/validate.spec.js

- Add option `disableDiffOnError`
- Update option validations
```
$ npm test
```

Add disableDiffOnError option

---

CHANGELOG.md
package.json
src/ci.js
test/ci.spec.js

Support for github actions using environment variables
https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables

Support for github actions

---

CHANGELOG.md
package.json
src/validate.js

Internal prop added to validate.js

internal prop added

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/runner.js
src/tunnel.js
src/validate.js
test/runner.spec.js
test/tunnel.spec.js
test/validate.spec.js

- Update default sauce connect version to 4.7.1
- Add scVersion option to sauce config
- Update saucelabs package
- Update docs
```
$ npm test
```

Update SC version. add scVersion option

---

CHANGELOG.md
package-lock.json
package.json
src/tunnel.js

* Bump saucelabs to v7.20
* Bump sc default to 4.8.1

Saucelabs and sc default updates
